spring:
    datasource:
      url: jdbc:mysql://localhost:3306/gotoviagens?useTimezone=true&serverTimezone=America/Sao_Paulo
      username: root
      password:

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibertnate:
            dialect: org.hibernate.dialect.MySQL8Dialect
    thymeleaf:
        cache: false
server:
  error:
    whitelabel:
      enabled: false